### ISSUE TITLE
Why not simulate in Niagara System editor with CPU？

### ISSUE THREAD

**Issue by Suikasxt** [monguri/UE4NiagaraSandbox#2]
First of all, thanks for your sharing.
I find that simulation with GPU is in Blueprint of Niagara System Module, but the one with CPU is in _SPH3DSimulatorCPU.cpp_. Can I just switch the Sim Target to CPU in Niagara Editor, so that I can easily combine SPH with other parts and get the performance analyzing？
By the way, I open SPH_3D_CPU_Map and can't see anything. Maybe it needs some adjustment and I'm trying to do so.

**Comment by monguri** [comment]
Thank you for your comment.
Sorry I was late to answer.

>Can I just switch the Sim Target to CPU in Niagara Editor, so that I can easily combine SPH with other parts and get the performance analyzing？

At SPH_3D/2D_CPU_Map, I am using SPH3D/2DSimulator.cpu and  NS_SPH_CPU.
They are CPU driven. Both simulation and niagara.
At SPH_3D/2D_GPU_Map, SPH_3D_GPU_Demo_Map and SPH_3D_GPU_Small_Demo_Map, I am using  NS_SPH_3D/2D_GPU.
They are using NeighborGrid3D which is valid only at GPU Sim.
If you switched off all bUseNeighborGrid3D flags, it might be suceeded compiling.
But without NeighborGrid3D, the performance will be worse about 2x - 2.5x. 

>By the way, I open SPH_3D_CPU_Map and can't see anything. Maybe it needs some adjustment and I'm trying to do so.

At SPH_3D/2D_CPU_Map, you have to start playing the level with SIE (simulation in editor).
If the niagara effect is very small in your viewport, you can focus it by the TargetPoint actor and fov command.
